##
# Code pipeline
##
#
# Main Buildkite pipeline for running code-related linters and tests.
#

docker_plugin_default_config: &docker_plugin_default_config
  image: "oasisprotocol/oasis-core-ci:${DOCKER_OASIS_CORE_CI_BASE_TAG}"
  always_pull: true
  workdir: /workdir
  volumes:
    - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
    - /var/lib/buildkite-agent/.codecov:/root/.codecov
    # IAS Development API keys.
    - /var/lib/buildkite-agent/.oasis-ias:/root/.oasis-ias
    # Shared Rust incremental compile caches.
    - /var/tmp/cargo_ic/debug:/var/tmp/artifacts/default/debug/incremental
    - /var/tmp/cargo_ic/debug_sgx:/var/tmp/artifacts/sgx/x86_64-unknown-linux-sgx/debug/incremental
    # Shared Rust package checkouts directory.
    - /var/tmp/cargo_pkg/git:/root/.cargo/git
    - /var/tmp/cargo_pkg/registry:/root/.cargo/registry
    # Shared Rust SGX standard library artifacts cache.
    - /var/tmp/xargo_cache:/root/.xargo
    # Shared Go package checkouts directory.
    - /var/tmp/go_pkg:/root/go/pkg
    # Intel SGX Application Enclave Services Manager (AESM) daemon running on
    # the Buildkite host.
    - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    # Propapage the tmpfs mount.
    - /tmp:/tmp
    # NOTE: When changing the environment variables below, also copy the changes
  # to the docker_plugin_sgx_config.
  environment:
    - "LC_ALL=C.UTF-8"
    - "LANG=C.UTF-8"
    - "CARGO_TARGET_DIR=/var/tmp/artifacts"
    - "CARGO_INSTALL_ROOT=/root/.cargo"
    - "CARGO_INCREMENTAL=0"
    - "GOPROXY=https://proxy.golang.org/"
  propagate-environment: true
  unconfined: true

docker_plugin_sgx_config: &docker_plugin_sgx_config
  <<: *docker_plugin_default_config
  devices:
    # Intel SGX device.
    - /dev/isgx
  environment:
    - "OASIS_TEE_HARDWARE=intel-sgx"
    # Copy of environment variables defined in docker_plugin_default_config.
    - "LC_ALL=C.UTF-8"
    - "LANG=C.UTF-8"
    - "CARGO_TARGET_DIR=/var/tmp/artifacts"
    - "CARGO_INSTALL_ROOT=/root/.cargo"
    - "CARGO_INCREMENTAL=0"
    - "GOPROXY=https://proxy.golang.org/"

docker_plugin: &docker_plugin
  oasislabs/docker#v3.0.1-oasis1:
    <<: *docker_plugin_default_config

docker_plugin_sgx: &docker_plugin_sgx
  oasislabs/docker#v3.0.1-oasis1:
    <<: *docker_plugin_sgx_config

retry: &retry_agent_failure
  automatic:
    - exit_status: 125 # ERRO[0092] error waiting for container: unexpected EOF
      limit: 2

steps:
  # Require explicit confirmation for some PRs to avoid CI spam.
  - block: Confirm CI run
    prompt: Run CI for this pull request?
    blocked_state: running
    if: |
      build.pull_request.id != null &&
      !(build.pull_request.labels includes "s:ready-ci") &&
      (
        build.pull_request.draft ||
        !(build.creator.teams includes "everyone")
      )

  ###########
  # Lint jobs
  ###########
  - label: Lint Go node
    command:
      - .buildkite/go/lint.sh
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  - label: Lint Rust crate versions
    command: .buildkite/rust/lint_crate_versions.sh
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  - label: Audit Rust dependencies for vulnerabilities
    command: .buildkite/rust/cargo_audit.sh
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  - label: Audit Go dependencies for vulnerabilities
    command: .buildkite/go/nancy_audit.sh
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  ############
  # Build jobs
  ############
  - label: Build Go node
    command:
      - .buildkite/go/build.sh
      - .buildkite/go/upload_artifacts.sh
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  - label: Build Rust runtime loader
    command:
      - .buildkite/rust/build_generic.sh /workdir -p oasis-core-runtime-loader

      # Upload the built artifacts.
      - cd /var/tmp/artifacts/default/debug
      - buildkite-agent artifact upload oasis-core-runtime-loader
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  ####################
  # Runtime build jobs
  ####################
  - label: Build key manager runtime
    command:
      - .buildkite/rust/build_runtime.sh tests/runtimes/simple-keymanager
      - .buildkite/rust/build_runtime.sh tests/runtimes/simple-keyvalue

      # Upload the built artifacts.
      - cd /var/tmp/artifacts/sgx/x86_64-fortanix-unknown-sgx/debug
      - buildkite-agent artifact upload simple-keymanager.sgxs
      - buildkite-agent artifact upload simple-keyvalue.sgxs
      - buildkite-agent artifact upload simple-keyvalue-upgrade.sgxs
      - buildkite-agent artifact upload simple-keymanager-upgrade.sgxs
      - cd /var/tmp/artifacts/default/debug
      - buildkite-agent artifact upload simple-keymanager
      - buildkite-agent artifact upload simple-keyvalue
      - buildkite-agent artifact upload simple-keyvalue-upgrade
      - buildkite-agent artifact upload simple-keymanager-upgrade
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  ###########
  # Test jobs
  ###########
  - label: Test Rust crates
    command:
      # Build storage interoperability test helpers first.
      - make build-helpers
      - export OASIS_STORAGE_PROTOCOL_SERVER_BINARY=$(realpath go/storage/mkvs/interop/mkvs-test-helpers)
      - .buildkite/rust/test_generic.sh .
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  # Wait for all jobs defined before this point
  # to finish running in parallel before continuing.
  - wait

  ###################################################
  # Test that build-fuzz still works (only on master)
  ###################################################
  - label: Test fuzz builds
    branches: master
    command:
      # TODO: Consider making this a part of the development Docker image.
      - go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
      - make -C go build-fuzz
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  #####################################
  # Test jobs requiring build artifacts
  #####################################
  - label: Test Go node
    command:
      - .buildkite/go/test_and_coverage.sh
    artifact_paths:
      - coverage-*.txt
      - /tmp/oasis-node-test_*/test-node.log
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  ###############
  # E2E test jobs
  ###############
  - label: E2E tests
    parallelism: 7
    timeout_in_minutes: 32
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      - .buildkite/scripts/test_e2e.sh
    artifact_paths:
      - coverage-merged-e2e-*.txt
      - /tmp/e2e/**/*.log
    env:
      OASIS_E2E_COVERAGE: enable
      TEST_BASE_DIR: /tmp
      # libp2p logging.
      IPFS_LOGGING: debug
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  ###########################
  # E2E test jobs - intel-sgx
  ###########################
  - label: E2E tests - intel-sgx (basic)
    branches: "!master !stable/*"
    timeout_in_minutes: 40
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      # Only run runtime scenarios as others do not use SGX.
      - .buildkite/scripts/test_e2e.sh --scenario e2e/runtime/runtime
    artifact_paths:
      - coverage-merged-e2e-*.txt
      - /tmp/e2e/**/*.log
    env:
      OASIS_E2E_COVERAGE: enable
      TEST_BASE_DIR: /tmp
      # libp2p logging.
      IPFS_LOGGING: debug
    agents:
      queue: intel-sgx
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin_sgx

  - label: E2E tests - intel-sgx (full)
    branches: master stable/*
    parallelism: 5
    timeout_in_minutes: 40
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      # Only run runtime scenarios as others do not use SGX.
      - .buildkite/scripts/test_e2e.sh --scenario e2e/runtime/.*
    artifact_paths:
      - coverage-merged-e2e-*.txt
      - /tmp/e2e/**/*.log
    env:
      OASIS_E2E_COVERAGE: enable
      OASIS_EXCLUDE_E2E: e2e/runtime/txsource-multi,e2e/runtime/txsource-multi-short
      TEST_BASE_DIR: /tmp
      # libp2p logging.
      IPFS_LOGGING: debug
    agents:
      queue: intel-sgx
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin_sgx

  ################################################
  # E2E test - intel-sgx with IAS (only on master)
  ################################################
  - label: E2E tests - intel-sgx - IAS
    branches: master stable/*
    timeout_in_minutes: 15
    command:
      - .buildkite/scripts/sgx_ias_tests.sh
    # A unique string to identify the step. The value is available in the
    # BUILDKITE_STEP_KEY and is used to ensure the generated coverage file
    # names are unique across this pipeline.
    key: sgx-ias
    artifact_paths:
      - coverage-merged-e2e-*.txt
      - /tmp/e2e/**/*.log
    env:
      OASIS_E2E_COVERAGE: enable
      TEST_BASE_DIR: /tmp
      # libp2p logging.
      IPFS_LOGGING: debug
    agents:
      queue: intel-sgx
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin_sgx

  ####################################
  # Rust coverage job (only on master)
  ####################################

  - label: Coverage Rust crates
    branches: master stable/*
    command:
      # Build storage interoperability test helpers first.
      - make build-helpers
      - export OASIS_STORAGE_PROTOCOL_SERVER_BINARY=$(realpath go/storage/mkvs/interop/mkvs-test-helpers)
      - .buildkite/rust/coverage.sh
    # Don't cause the build to fail, as tarpaulin is pretty unstable at the moment.
    soft_fail: true
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin

  # Wait for all jobs defined before this point
  # to finish running in parallel before continuing.
  - wait

  ###########################
  # Merge coverage and upload
  ###########################

  - label: "Merge and upload coverage"
    command:
      - .buildkite/scripts/merge_coverage.sh
      - .buildkite/scripts/upload_coverage.sh
    artifact_paths:
      - merged-coverage.txt
    soft_fail: true
    retry:
      <<: *retry_agent_failure
    plugins:
      <<: *docker_plugin
